name: CI-pipeline

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request: 
    branches: 
      - dev
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Compile
      run: mvn -B compile
      env: 
        KEY: ${{ secrets.KEY }}
    - name: Test
      run: mvn -B test
    - name: Package
      run: mvn -B package
